### ISSUE TITLE
iPhone: SampleBufferAppendFailed

### ISSUE THREAD

**Issue by jtkeyva** [chipweinberger/flutter_quick_video_encoder#1]
Getting this running the example

flutter: Error: PlatformException(SampleBufferAppendFailed, Failed to append video sample buffer, The operation could not be completed, null)

**Comment by chipweinberger** [comment]
wow love how quickly you are already using this plugin =)

I was getting that error too and I needed to make sure the output directory actually existed.

can you try adding this code and then opening a PR?

```
  void _createIntermediateDirectories(String filepath) {
    File file = File(filepath);
    Directory dir = file.parent;
    if (!dir.existsSync()) {
      dir.createSync(recursive: true);
    }
  }
```

**Comment by chipweinberger** [comment]
should be fixed in 1.0.2 now

**Comment by jtkeyva** [comment]
yeah thanks for doing this. i'm excited about this and eliminating ffmpeg. media_tool seems cool too but still in early stages.

i'm still getting the same error in 1.0.4

i may make an example using the camera and share_plus package or something to show the original file size and the new encoded size

**Comment by chipweinberger** [comment]
I haven't tested ios yet. only mac. 

so maybe there's some difference

**Comment by jtkeyva** [comment]
anything i can do to help?

**Comment by chipweinberger** [comment]
if you find the problem open a PR :)

**Comment by chipweinberger** [comment]
iOS is now fixed in 1.1.0
